# Generated by Django 6.0.2 on 2026-02-10 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('idade', models.IntegerField()),
                ('localizacao', models.CharField(max_length=200)),
                ('altura', models.FloatField()),
                ('peso', models.FloatField()),
                ('instagram', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
