# Generated by Django 6.0.2 on 2026-02-10 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('tatuagens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('tamanho_cm', models.FloatField()),
                ('parte_corpo', models.CharField(max_length=100)),
                ('preco_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('analise', 'Em análise'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado')], default='pendente', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('estilo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tatuagens.estilotattoo')),
            ],
        ),
    ]
