# Generated by Django 6.0.2 on 2026-02-12 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0002_alter_orcamento_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('estilo', models.CharField(max_length=50)),
                ('imagem', models.ImageField(upload_to='portfolio/')),
                ('data_postagem', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
